// <auto-generated />
using System;
using Clinica.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinica.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    partial class ClinicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinica.Domain.Entities.ConsultaMedica", b =>
                {
                    b.Property<int>("ConsultaMedicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaMedicaId"));

                    b.Property<string>("Anamnesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamenFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotasInternas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("ConsultaMedicaId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("ConsultasMedicas");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Consultorio", b =>
                {
                    b.Property<int>("ConsultorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultorioId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsultorioId");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Diagnostico", b =>
                {
                    b.Property<int>("DiagnosticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosticoId"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsultaMedicaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosticoId");

                    b.HasIndex("ConsultaMedicaId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecialidadId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicoId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ObraSocial", b =>
                {
                    b.Property<int>("ObraSocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraSocialId"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraSocialId");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroHistoriaClinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanObraSocialId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacienteId");

                    b.HasIndex("ObraSocialId");

                    b.HasIndex("PlanObraSocialId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.PlanObraSocial", b =>
                {
                    b.Property<int>("PlanObraSocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanObraSocialId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.HasKey("PlanObraSocialId");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("PlanesObraSocial");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.PlanObraSocial", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany("Planes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaId"));

                    b.Property<int>("ConsultaMedicaId")
                        .HasColumnType("int");

                    b.Property<string>("Dosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecetaId");

                    b.HasIndex("ConsultaMedicaId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<int?>("ConsultaMedicaId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsultorioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("TurnoId");

                    b.HasIndex("ConsultaMedicaId")
                        .IsUnique()
                        .HasFilter("[ConsultaMedicaId] IS NOT NULL");

                    b.HasIndex("ConsultorioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ConsultaMedica", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Diagnostico", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.ConsultaMedica", "ConsultaMedica")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaMedica");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Medico", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany("Pacientes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.PlanObraSocial", "PlanObraSocial")
                        .WithMany("Pacientes")
                        .HasForeignKey("PlanObraSocialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ObraSocial");

                    b.Navigation("PlanObraSocial");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.PlanObraSocial", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany("Planes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Receta", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.ConsultaMedica", "ConsultaMedica")
                        .WithMany("Recetas")
                        .HasForeignKey("ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaMedica");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Turno", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.ConsultaMedica", "ConsultaMedica")
                        .WithOne()
                        .HasForeignKey("Clinica.Domain.Entities.Turno", "ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Consultorio", "Consultorio")
                        .WithMany("Turnos")
                        .HasForeignKey("ConsultorioId");

                    b.HasOne("Clinica.Domain.Entities.Medico", "Medico")
                        .WithMany("Turnos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId");

                    b.Navigation("ConsultaMedica");

                    b.Navigation("Consultorio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ConsultaMedica", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Consultorio", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ObraSocial", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Planes");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.PlanObraSocial", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
